Repository input-output-hk/marlowe-playground, pull requests merged in 2023-11, with the labels that each got.

#50 Bump IOGX v4
  doc/default.nix
  flake.lock
  flake.nix
  marlowe-playground-client/README.md
  nix/cabal-project.nix
  nix/ci.nix
  nix/easy-purescript-nix.nix
  nix/formatters.nix
  nix/generated-purescript.nix
  nix/haskell.nix
  nix/marlowe-playground-client.nix
  nix/marlowe-playground/generated-purescript.nix
  nix/npm-deps-hash.nix
  nix/oci-images.nix
  nix/operables.nix
  nix/outputs.nix
  nix/per-system-outputs.nix
  nix/playwright.nix
  nix/project.nix
  nix/scripts.nix
  nix/shell.nix
  nix/spago-packages.nix
  package-lock.json
Labels: No Changelog Required

#58 PLT-7568 - Make greying out of boilerplate of TypeScript editor darker
  changelog.d/20231120_125001_pablo.lamela_PLT_7568.md
  marlowe-playground-client/static/css/main.css
Labels: enhancement

#57 PLT-3985 - Show initial time for counterexamples in a human readable way
  changelog.d/20231116_023007_pablo.lamela_PLT_3985.md
  marlowe-playground-client/README.md
  marlowe-playground-client/generated/Marlowe/Symbolic/Types/Response.purs
  marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
  marlowe-playground-server/app/PSGenerator.hs
  marlowe-symbolic/src/Marlowe/Symbolic/Server.hs
  marlowe-symbolic/src/Marlowe/Symbolic/Types/Response.hs
  nix/shell.nix
  web-common-marlowe/src/Humanize.purs
Labels: bug
