Repository input-output-hk/marlowe-playground, pull requests merged in 2024-01, with the labels that each got.

#60 Add PAT for bypassing branch protection for autocommit
  .github/workflows/autocommit.yml
Labels: No Changelog Required

#63 Fix PS-generator and generated files to match
  marlowe-playground-client/generated/Examples/Haskell/Contracts.purs
  marlowe-playground-client/generated/Examples/Marlowe/Contracts.purs
  marlowe-playground-server/contracts/EscrowWithCollateral.hs
Labels: bug, No Changelog Required

#64 PLT-8827 - Check token names and currency symbols
  changelog.d/20240117_023242_pablo.lamela_PLT_8827.md
  marlowe-playground-client/generated/Examples/Haskell/Contracts.purs
  marlowe-playground-client/generated/Examples/Marlowe/Contracts.purs
  marlowe-playground-client/spago.dhall
  marlowe-playground-client/src/Examples/JS/Contracts.purs
  marlowe-playground-client/src/Marlowe/Linter.purs
  marlowe-playground-client/src/Marlowe/LinterText.purs
  marlowe-playground-client/test/Marlowe/LintTests.purs
  marlowe-playground-server/contracts/Swap.hs
  nix/spago-packages.nix
  packages.dhall
  web-common-marlowe/src/Examples/PureScript/Swap.purs
Labels: enhancement
